# Generated by Django 3.2.25 on 2024-04-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0002_rename_product_excavator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavator',
            name='production_year',
            field=models.IntegerField(),
        ),
    ]
